# Generated by Django 4.0.4 on 2022-05-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id_num', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='almacenamiento',
            fields=[
                ('id_num', models.AutoField(primary_key=True, serialize=False)),
                ('id_producto', models.BigIntegerField()),
                ('id_almacen', models.BigIntegerField()),
                ('cantidad', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_num', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id_num', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='equipo_asignado',
            fields=[
                ('id_num', models.AutoField(primary_key=True, serialize=False)),
                ('id_producto', models.BigIntegerField()),
                ('id_operador', models.BigIntegerField()),
                ('status', models.BooleanField()),
                ('cantidad', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id_num', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.BigIntegerField()),
                ('id_cargo', models.BigIntegerField()),
                ('id_sede', models.BigIntegerField()),
                ('id_depart', models.BigIntegerField()),
                ('fecha_asig', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_num', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('marca', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id_num', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
